/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import HolographicMaterial from './HologramShader'
import { degToRad } from 'three/src/math/MathUtils'

// Minimal hologram config for clean aesthetic
const minimalHologramProps = {
  hologramColor: "#4af0ff",      // Soft cyan
  secondaryColor: "#2dd4bf",     // Teal accent
  accentColor: "#4af0ff",        // Purple highlight
  hologramBrightness: 0.,
  hologramOpacity: 0.4,
  fresnelOpacity: 0.25,
  fresnelAmount: 1.2,
  scanlineSize: 2.0,
  scanlineSpeed: 0.45,
  enableGrid: true,
  gridSize: 3.0,
  gridLineWidth: 2.0,
  enableHexPattern: false,
  enableDataStreams: false,
  enablePulseWaves: true,
  pulseSpeed: 1.0,
  wireframeIntensity: 0.0,
  glitchIntensity: 0.0,
  chromaticStrength: 0.,
}

export function Model(props) {
  const { nodes, materials } = useGLTF('model/partsTogether.glb')

  return (
    <group scale={0.014}  {...props} rotation={[degToRad(90), degToRad(90), degToRad(0)]} dispose={null}>
      <group position={[0, 60.041, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_1.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_2.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_3.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_4.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_5.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_6.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_7.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_8.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_9.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_low_Body_Main_0_10.geometry}
        >
          <HolographicMaterial {...minimalHologramProps} />
        </mesh>
      </group>
    </group>
  )
}

