/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Scuderia Morello (https://sketchfab.com/scudmorello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f6-boxer-engine-5700259eeb494b8f8a0b8f63486c59cc
Title: F6 Boxer Engine
*/

import React, { forwardRef, useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { degToRad } from 'three/src/math/MathUtils'
import * as THREE from 'three'
import '../shaders/ElectricModelMaterial'

// Electric mesh component that applies the shader
function ElectricMesh({ geometry, material, electricColor, intensity, gridScale, blendMode }) {
    const meshRef = useRef()
    const materialRef = useRef()
    
    // Get texture from original material with proper settings
    const texture = useMemo(() => {
        if (material.map) {
            // Clone the texture to avoid modifying the original
            const tex = material.map.clone()
            tex.needsUpdate = true
            tex.colorSpace = THREE.SRGBColorSpace
            tex.minFilter = THREE.LinearMipmapLinearFilter
            tex.magFilter = THREE.LinearFilter
            tex.anisotropy = 16
            return tex
        }
        // Create a simple color texture if no map exists
        const canvas = document.createElement('canvas')
        canvas.width = 64
        canvas.height = 64
        const ctx = canvas.getContext('2d')
        const color = material.color || new THREE.Color(0.5, 0.5, 0.5)
        ctx.fillStyle = `rgb(${Math.round(color.r * 255)}, ${Math.round(color.g * 255)}, ${Math.round(color.b * 255)})`
        ctx.fillRect(0, 0, 64, 64)
        const tex = new THREE.CanvasTexture(canvas)
        tex.colorSpace = THREE.SRGBColorSpace
        tex.needsUpdate = true
        return tex
    }, [material])
    
    useFrame((state) => {
        if (materialRef.current) {
            materialRef.current.uTime = state.clock.elapsedTime
        }
    })
    
    return (
        <mesh ref={meshRef} geometry={geometry} castShadow receiveShadow>
            <electricModelMaterial
                ref={materialRef}
                uMap={texture}
                uColor={electricColor}
                uIntensity={intensity}
                uGridScale={gridScale}
                uGridLineScale={0.1}
                uElectricPower={7.0}
                uBlendMode={blendMode}
                transparent={false}
                side={THREE.DoubleSide}
            />
        </mesh>
    )
}

const V6Enigine = forwardRef(function V6Enigine({ 
    electricEffect = true,
    electricColor = new THREE.Color(0.0, 1.0, 0.4),
    electricIntensity = 1.5,
    gridScale = 10.0,
    blendMode = 0.5,
    ...props 
}, ref) {
    const { nodes, materials } = useGLTF('/model/f6_boxer_engine.glb')
    
    // All mesh configurations
    const meshConfigs = [
        { geometry: nodes.Object_2.geometry, material: materials.Spada_1SG },
        { geometry: nodes.Object_3.geometry, material: materials.blinn10SG },
        { geometry: nodes.Object_4.geometry, material: materials.blinn6SG },
        { geometry: nodes.Object_5.geometry, material: materials.lambert11SG },
        { geometry: nodes.Object_6.geometry, material: materials.blinn14SG },
        { geometry: nodes.Object_7.geometry, material: materials.blinn15SG },
        { geometry: nodes.Object_8.geometry, material: materials.blinn3SG },
        { geometry: nodes.Object_9.geometry, material: materials.blinn4SG },
        { geometry: nodes.Object_10.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_11.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_12.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_13.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_14.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_15.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_16.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_17.geometry, material: materials.initialShadingGroup },
        { geometry: nodes.Object_18.geometry, material: materials.lambert10SG },
        { geometry: nodes.Object_19.geometry, material: materials.lambert2SG },
        { geometry: nodes.Object_20.geometry, material: materials.lambert3SG },
        { geometry: nodes.Object_21.geometry, material: materials.lambert4SG },
        { geometry: nodes.Object_22.geometry, material: materials.typeBlinn1SG },
    ]
    
    return (
        <group ref={ref}>
            <group scale={0.2} position={[0, 0, 0]} rotation={[0, degToRad(90), 0]} {...props} dispose={null}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    {electricEffect ? (
                        // Render with electric shader
                        meshConfigs.map((config, i) => (
                            <ElectricMesh
                                key={i}
                                geometry={config.geometry}
                                material={config.material}
                                electricColor={electricColor}
                                intensity={electricIntensity}
                                gridScale={gridScale}
                                blendMode={blendMode}
                            />
                        ))
                    ) : (
                        // Render with original materials
                        meshConfigs.map((config, i) => (
                            <mesh
                                key={i}
                                castShadow
                                receiveShadow
                                geometry={config.geometry}
                                material={config.material}
                            />
                        ))
                    )}
                </group>
            </group>
        </group>
    )
})

export default V6Enigine

useGLTF.preload('/model/f6_boxer_engine.glb')
