/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Scuderia Morello (https://sketchfab.com/scudmorello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f6-boxer-engine-5700259eeb494b8f8a0b8f63486c59cc
Title: F6 Boxer Engine
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { degToRad } from 'three/src/math/MathUtils'
import * as THREE from 'three'
import RichetMaterial from '../shaders/HologramShader'

// Hologram mesh component that applies the shader
function HologramMesh({ geometry }) {
    const meshRef = useRef()
    
    return (
        <mesh ref={meshRef} geometry={geometry} castShadow receiveShadow>
            <RichetMaterial
               
                hologramBrightness={0.}
                hologramOpacity={0.4}
                fresnelOpacity={0.}
                fresnelAmount={1.2}
                scanlineSize={2.0}
                scanlineSpeed={0.45}
                enableGrid={true}
                gridSize={3.0}
                brightness={1.0}
                blackPatchScale={0}
                gridLineWidth={2.0}
                enableHexPattern={true}
                enableDataStreams={true}
                enablePulseWaves={true}
                contrast={0.2}
                pulseSpeed={1.0}
                wireframeIntensity={0.}
                glitchIntensity={0}
                chromaticStrength={0.}
            />
        </mesh>
    )
}

const V6Enigine = forwardRef(function V6Enigine({ 
    hologramEffect = true,
    ...props 
}, ref) {
    const { nodes, materials } = useGLTF('/model/f6_boxer_engine.glb')
    
    // All mesh configurations
    const meshConfigs = [
        { geometry: nodes.Object_2.geometry, material: materials.Spada_1SG },
        { geometry: nodes.Object_3.geometry, material: materials.blinn10SG },
        { geometry: nodes.Object_4.geometry, material: materials.blinn6SG },
        { geometry: nodes.Object_5.geometry, material: materials.lambert11SG },
        { geometry: nodes.Object_6.geometry, material: materials.blinn14SG },
        { geometry: nodes.Object_7.geometry, material: materials.blinn15SG },
        { geometry: nodes.Object_8.geometry, material: materials.blinn3SG },
        { geometry: nodes.Object_9.geometry, material: materials.blinn4SG },
        { geometry: nodes.Object_10.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_11.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_12.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_13.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_14.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_15.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_16.geometry, material: materials.blinn5SG },
        { geometry: nodes.Object_17.geometry, material: materials.initialShadingGroup },
        { geometry: nodes.Object_18.geometry, material: materials.lambert10SG },
        { geometry: nodes.Object_19.geometry, material: materials.lambert2SG },
        { geometry: nodes.Object_20.geometry, material: materials.lambert3SG },
        { geometry: nodes.Object_21.geometry, material: materials.lambert4SG },
        { geometry: nodes.Object_22.geometry, material: materials.typeBlinn1SG },
    ]
    
    return (
        <group ref={ref}>
            <group scale={0.2} position={[0, 0, 0]} rotation={[0, degToRad(90), 0]} {...props} dispose={null}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    {hologramEffect ? (
                        // Render with hologram shader
                        meshConfigs.map((config, i) => (
                            <HologramMesh
                                key={i}
                                geometry={config.geometry}
                            />
                        ))
                    ) : (
                        // Render with original materials
                        meshConfigs.map((config, i) => (
                            <mesh
                                key={i}
                                castShadow
                                receiveShadow
                                geometry={config.geometry}
                                material={config.material}
                            />
                        ))
                    )}
                </group>
            </group>
        </group>
    )
})

export default V6Enigine

useGLTF.preload('/model/f6_boxer_engine.glb')
